### ISSUE TITLE
关于人员管理，人员各系统名称建议。

### ISSUE THREAD

**Issue by skomefen** [wearestar/mars_old#14]
由于群成员有22位，而鉴于各位的微信号，Github账号和禅道管理系统的账号都不一样，所以为了管理方便。我建议禅到管理系统里每个人的用户名改成微信名---Github账号名

如果我们要用slack工具作为聊天工具的话，slack用户名也改为微信名。

欢迎拍砖

**Comment by oathsign** [comment]
不用改用户名 改真实姓名即可 用户名是登录账号

**Comment by ivanberry** [comment]
若使用Slack的话，保持同步就好，同禅道名。
