### ISSUE TITLE
战神博客第一期团队成员需求个人表

### ISSUE THREAD

**Issue by skomefen** [wearestar/mars_old#19]
我提了个战神博客第一期团队成员需求个人表到**禅道的**
_所有文档库->产品->战神博客->项目库->战神第一期->附件库里面_
建议大家把文件名改为"战神博客第一期团队成员需求个人表-'微信名'.xlsx"提交上来

**Comment by skomefen** [comment]
提交到禅道里面

**Comment by oathsign** [comment]
好
