### ISSUE TITLE
关于本项目前端的一点想法，欢迎拍砖

### ISSUE THREAD

**Issue by Zhongwei1986** [wearestar/mars_old#2]
- 先搭建结构框架，再添加样式和交互
一般博客网站是大概会分几层：博客网站首页，分类首页，个人博客首页，博文页面等。当我们确定技术栈之后，应该有一个初版的交互设计稿，根据初版设计稿来完成大框架的基础建设。
完成基本的框架后，交互设计稿应该有一个比较详细的版本了，再根据这个版本来进行样式和交互设计。
建议分两组人来完成，一组人做样式，一组人做交互，然后互相review对方代码。

- 前后端数据接口
在进行交互设计稿的同时，需要与后端讨论前后端交互的数据格式(JSON/HTML)，最好是有一份前后统一的接口定义表，应包含但不限于：变量名，变量类型，变量作用，变量示例

**Comment by oathsign** [comment]
@Zhongwei1986 你说的是正确的项目开发计划。任何东西，只有真的做了，自己用了，才会意识到哪里需要**改动**，哪里需要更加**精致**。这些改动不仅仅局限于所见的页面，还有交互，还有源码的**可读性**等等。

### 初期的计划是这样的:

> 1. 完成基本的开发规范，包括html,css,javascript,php等在内的各种文档的格式规范,变量声明规范等等。
> 2. 建立知识库与开发日记，方便大家查阅资料交流心得。知识库用wiki，开发日记暂时用issue。
> 3. 建立项目管理系统，其实项目本身是有个Projects的迷你项目管理系统的，不过要跟其他几个模块联合使用才能发挥它的作用。
> 4. 进行人员分配，前台后台测试以及文档编写等等，其实是都需要人的。我并不强制某人必须在那个岗位，因为这个项目本身就是期望能让大家有所成长的，所以我希望大家都能接触接触。不过有个前提：**做事要有始有终！** 一定要真正的熟练掌握了某一块，再去做其他，不要 **被自己的热情冲昏头脑！**
> 5. 确立一系列粗线条可开发的需求，对需求进行细分整理。
> 6. 根据需求，提出可执行的任务，分配给队员。
> 7. 剩下的便是不断地开发功能，测试功能，上线。
