### ISSUE TITLE
Mars Blog 交互设计的设计规范、方案构建、链接资源、意见整理和进程安排

### ISSUE THREAD

**Issue by j7gong** [wearestar/mars_old#21]
# Mars Blog 交互设计的资料整理以及方案构建
## 1 交互设计的设计规范和组件化开发
<br>
1.1 这次Mars Blog项目我们采用谷歌设计规范: 
<a href="https://material.io/guidelines/material-design/introduction.html" >英文规范</a>
<a href="https://www.douban.com/note/374369815/" >中文规范</a>
<br>
1.2 组件化设计和开发的思维模式: 
<a href="http://www.shejidaren.com/ju-jian-hua-kai-fa.html" >组件化设计和开发</a>

## 2 方案构建
这是Mars Blog初版设计的首页界面。
<br>
![Homepage](http://onnyhcusx.bkt.clouddn.com/MarsBlog_homepage.jpg)
<br>
这是Mars Blog初版设计的用户界面。
![Userpage](http://onnyhcusx.bkt.clouddn.com/Mars-Blog-User.jpg)
这是Mars Blog初版设计的博客界面。
![Blogpage](http://onnyhcusx.bkt.clouddn.com/blog-page.jpg)
## 3 链接资源
<br>
3.1 <a href="https://zhuanlan.zhihu.com/p/19617848?columnSlug=youwenwen" >交互设计的一些理念</a>(中文）
<br>
3.2 <a href="https://land-book.com" >为你提供设计灵感</a>（英文）
<br>
3.3 <a href="http://www.colormatters.com/color-and-design/basic-color-theory" >了解颜色设计</a>
(英文)<br>
3.4 <a href="https://github.com/itmeo/webgradients" >渐变色CSS库</a>（英文）<br>
3.5 <a href="https://thenextweb.com/dd/2012/04/23/searching-for-design-inspiration-heres-97-of-the-best-places-too-look/#.tnw_EWhvbpWy" >设计网址</a>（英文）<br>
3.6 <a href="http://www.bootcss.com/p/layoutit/" >bootstrap布局式工具</a>
<br>

## 4 意见整理
5.1 语言支持中英切换 <br>
5.2 那设计主题就以宇宙和行星为方向<br>
5.3 用户界面有队友要求可拖拽功能。<br>
5.4 关于编辑推荐模块的设想: (1)不如搞一个算法，按某个标准推荐；(2) 可以考虑有个用户推荐模块
(3)或者搞一个用户轮流当编辑的机制的模块<br>
5.5 还有个待定问题是 logo的设计，看大家对Mars Blog有什么想法和创意<br> 

## 5 进程安排
5.1 各位用户队友们，对界面设计有什么意见和特殊需求在Mar.31日11pm以前随时提。<br>
5.2 在设计稿完善之前，所有的想法都非常有价值~ 大家都是第一批用户，我们是在为自己代言。<br>
5.3 组件代码是在设计图整好了之后，先分模块，再进行整理和分派相关任务。相关文档以及源码和参数会在周日进行pr和issue的。

**Comment by ivanberry** [comment]
链接地址建议使用markdown语法，避免复制链接访问eg: 
[谷歌](http://www.google.com)

**Comment by j7gong** [comment]
不知道为什么markdown的链接语法用不了，心塞，最后用的html

**Comment by skomefen** [comment]
这个答案不知道有没有帮助，可以看一下，关于[设计图标][1]的。

[1]: https://zhuanlan.zhihu.com/p/26073777?utm_source=wechat_session&utm_medium=social  "设计图标"
@j7gong

**Comment by j7gong** [comment]
@skomefen 很赞呐 谢谢~ 这块承包给你肿么样:)

**Comment by skomefen** [comment]
额。。我试一下 @j7gong

**Comment by oathsign** [comment]
# 交互稿写的很不错 @j7gong

**Comment by oathsign** [comment]
1. 像背景颜色，模块颜色，模块位置，都可以做成让用户自己设置

2. 用户还可以在左侧添加栏中，任意增减喜欢的模块元素（这些元素之后可以玩升级流收费流也好...）

3. 首页页面下周末我可以再美化一下，主要是logo的设计和背景图案的设计，这个可以先放放

**Comment by oathsign** [comment]
如果有实现 请提交代码 @j7gong
