### ISSUE TITLE
建议把文档放到Wiki目录

### ISSUE THREAD

**Issue by unclexiao** [wearestar/mars_old#28]
建议把相关文档（mars/docs/）放到**Wiki**目录，方便大家留言提出疑惑或想法

**Comment by ivanberry** [comment]
同意，不过现在资料还不足够，以后就要好好整理了

**Comment by oathsign** [comment]
资料统一放到gitbook里进行管理 放wiki里如果库挪了就没了

**Comment by GHLgh** [comment]
@oathsign 可以发一下gitbook的链接吗

**Comment by oathsign** [comment]
https://www.gitbook.com/@oathsign/dashboard  @GHLgh 文档全在这个地址
