### ISSUE TITLE
关于用户登录有个小细节想问下大家

### ISSUE THREAD

**Issue by skomefen** [wearestar/mars_old#29]
你们觉得保持登陆状态应该怎样设置

根据建议，现在方案修改为：

1、每次访问网站都要重新登陆

2、登陆的时候可以选择设置自动登录的有效时间，有效时间内自动登录，其他机器有登陆网站则无法自动登录。
//通过生成唯一令牌标注是否为上次登录的机器

判断逻辑如下：

- 验证是否包含自动登录cookie

    -  未包含
        - 则用户登录时
            - 未选择自动登录有效时间。生成新的令牌存储数据库。跳出程序。
            - 选择自动登录有效时间。生成新的令牌存储数据库，创建cookie发送到浏览器。cookie包含自动登录过期时间，令牌，用户名，以及一个（用自动登录过期时间，令牌，用户名，密码，一个特殊的key加密）的md5信息摘要。
    -  包含
         - 验证登陆时间是否过期
            - 未通过则跳出程序
         - 验证令牌
            - 未通过则跳出程序
         - 验证用户名密码
            - 未通过则跳出程序
         - 验证加密的md5信息摘要
            - 未通过则跳出程序
         - 登陆，生成新的令牌存储数据库，创建cookie发送到浏览器。同上组装cookie信息（包含新的令牌）。

3、登陆之后即使关闭网页，只要没有按退出登陆，下次访问可以直接登陆。一段时间（固定的间隔时长）没有登陆（如三天内）则不能自动登录。在其他机器登陆则原来机器无法自动登陆。
/**
每次登陆都会生成新的自动登录到期时间。
这固定的间隔上次登录时长是由网站管理员决定。由网站配置信息或者网站管理系统修改。默认值设为两天。
*/

判断逻辑如下：

- 验证是否包含自动登录cookie

    -  未包含
        - 则用户登录时
            - 未选择自动登录。生成新的令牌存储数据库。跳出程序。
            - 选择自动登录。生成新的令牌存储数据库，创建cookie发送到浏览器。cookie包含自动登录过期时间，令牌，用户名，以及一个（用自动登录过期时间，令牌，用户名，密码，一个特殊的key加密）的md5信息摘要。
    -  包含
         - 验证登陆时间是否过期
            - 未通过则跳出程序
         - 验证令牌
            - 未通过则跳出程序
         - 验证用户名密码
            - 未通过则跳出程序
         - 验证加密的md5信息摘要
            - 未通过则跳出程序
         - 登陆，生成新的令牌存储数据库，生成新的自动登录过期时间，创建cookie发送到浏览器。同上组装cookie信息（包含新的令牌和新的自动登录过期时间）。

_方案2和方案3区别：_

- 方案2是需要用户主动设置自动登录有效时间，该时间在用户第二次设置自动登陆有效时间之前不会变化。

- 方案3是用户每次登陆网站都会重新生成新的到期时间。而判断是否到期两个判断条件

    - 根据距离上次登陆网站间隔时长

    - 是否是上次登陆的机器。

其实方案3最关键的问题还是安全问题。不过博客安全需求没这么高罢了。

貌似bilibili和QQ邮箱都是方案3的形式，只是不知道它时间设置多长。

有其他方案欢迎补充。目前都认为方案3好。
这设置的时间我们不写死。默认改为两天好了。

**Comment by j7gong** [comment]
给方案3投一票，时间定为一周？

**Comment by GHLgh** [comment]
问一下，当使用方案 2 时，如果在有效时间内关闭网页然后再打开网站的话，也是会自动登陆的吗？如果是的话，跟方案 3 有什么重大的区别？

就现在的三个方案来看，方案 3 比较好：
* 当用户不小心关闭页面时，免去重复登陆的操作
* 如果用户在公共机器上登陆了，之后可以直接在其他机器登陆来防止在公共机器自动登陆
  * 不过应当在用户登陆时，有是否允许自动登陆的选项

保存cookie的时间不需要太长，一到三天应该就可以了：
* 主要是为了让用户在短时间内关闭打开页面时，不需要重复登陆操作。如果用户长期使用同一个机器登陆网站的话，浏览器的记住密码功能已经减少了大量的操作。
* 如果保存时间太长的话，可能会有潜在的账号安全问题（ex. 当用户在公共机器上登陆了，但没有及时登出/在个人机器上再登陆时）。

**Comment by skomefen** [comment]
@j7gong 时间太长容易出现安全性问题

**Comment by j7gong** [comment]
嗯呐 好的 楼上解释的很清楚

**Comment by zephyrJS** [comment]
个人也支持方案三来执行登录方案。但一楼的描述是否有点问题呢，我觉得判断依据应该是【距离上次的登录间隔时长】，而不是【距离上次访问网站的时长】。

**Comment by skomefen** [comment]
@zephyrJS  有道理，逻辑应该改为距离上次登录间隔时长。

**Comment by skomefen** [comment]
话说老大，我看了下需求，我们第一期的项目里面木有提供给游客登陆注册的需求。而暂时用户都是内部成员在后台登陆。那是不是就不在前台提供登陆接口了？ @oathsign

**Comment by oathsign** [comment]
没有写 一切都是空谈 有问题欢迎提pr 不要再讨论了
