### ISSUE TITLE
文档分享

### ISSUE THREAD

**Issue by huasheng28** [wearestar/mars_old#4]
[PHP与MySQL WEB开发圣经中文版](http://pan.baidu.com/s/1qYz0tGg)

**Comment by huasheng28** [comment]
[slack地址](https://mars-pro.slack.com/shared_invite/MTU4OTk1NTI0MDUwLTE0OTAzMDY1NDUtNzFmMjhmNDAwMQ)

**Comment by ivanberry** [comment]
[PHP与MySQL英文版](http://ahvaz.ist.unomaha.edu/azad/temp/softarch/05-welling-php-mysql-web.pdf)

**Comment by oathsign** [comment]
# 禁止发送盗版读物链接 除此之外 欢迎提交各种好玩和好用的读物音像链接
